### ISSUE TITLE
about the intronic signal

### ISSUE THREAD

**Issue by sharply-x** [rnabioco/mzt-introns#2]
hello, I try to repeat your analysis. It's a good project which makes a nearly newbie could finish it. And I found that in the pipeline the intronic signal will be allocated to only one transcript if there're more than one transcripts(eg. there are two transcripts A,B that have the same intron, then only A or only B has intronic signal ). Is this will affect the downstream analysis in transcript-level?
And I noticed that in your paper when you do transcript isoform analysis, first we find the significant genes, then we select the representative maternal or zygotic isoform respectively. If there're more than one isoforms, will it be ignored it ? Why not directly  find the significant transcript isoform?

**Comment by sharply-x** [comment]
and in the vignette.rmd file
![R](https://user-images.githubusercontent.com/73643937/230898773-735f28d9-e92b-46cb-9a4d-d89ef7d555c9.png)
the design formula is '~mzt+strain' why not '~strain+mzt' which represent the comparison mzt vs zyg

**Comment by kriemo** [comment]
Hi, thanks for your interest in our method. Regarding your first question, the transcript level intron signals are present in the salmon outputs. You can change the tximport command to keep transcript-level estimates if you'd like to examine the behavior of individual introns and transcripts. One impact of using transcript-level counts is that you'll likely have fewer counts per intron, compared to summing all introns to a gene-level. Depending on the read depth of your libraries this could reduce your sensitivity to detect an intron signal. 

e.g. using tximport
```R
txi <- tximport(salmon_files, 
                type = "salmon",
                tx2gene = gene2intron,
                txOut = TRUE)

# the introns are after the transcript (exonic) counts 
tail(txi$counts)
               [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
FBtr0344847-I2    0    0    0    0    0    0    0    0    0 0.000
FBtr0113705-I1    0    0    0    0    0    0    0    0    0 0.000
FBtr0300704-I2    0    0    0    0    0    0    0    0    0 3.029
FBtr0113781-I     0    0    0    0    0    0    0    0    0 0.000
FBtr0113781-I1    0    0    0    1    0    0    0    0    0 0.000
FBtr0113781-I2    0    0    0    0    0    0    0    0    0 0.000
```

Regarding the vignette, it doesn't change the results to use ` ~ mzt + stain` if you pass `name = "mzt_zygotic_vs_maternal"` to the `results()` DESeq2 function.  However I agree that using the `~ strain + mzt` design is more clear, and commonly used, so I'll change it in the vignette.

**Comment by sharply-x** [comment]
Thank you for all your assistance. 
I tried 'txOut=T'. However, when I search the transcripts of hrg(FBgn0015949), there's only one transcript having all intronic signal while other transcripts lost some intronic signal because they are sharing the same introns. The following screenshot:
![R](https://user-images.githubusercontent.com/73643937/231026722-0787d641-68b8-47d0-8bff-f7113d20eda6.png)
And I have sent an email for some questions last weekend, maybe it was judged as spam. Would you please have a look? Thanks very much.

**Comment by kriemo** [comment]
I see your email now, yes it went to spam so I missed it. I'll respond via email, thanks.
